### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by ettolo** [sjaakp/yii2-pluto#17]
Hi, in attach italian translation. 
[pluto_IT.zip](https://github.com/sjaakp/yii2-pluto/files/4204241/pluto_IT.zip)

**Comment by sjaakp** [comment]
Grazie mille!

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: ettolo <notifications@github.com> 
Verzonden: vrijdag 14 februari 2020 12:27
Aan: sjaakp/yii2-pluto <yii2-pluto@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [sjaakp/yii2-pluto] Italian translation (#17)

 

Hi, in attach italian translation.
pluto_IT.zip <https://github.com/sjaakp/yii2-pluto/files/4204241/pluto_IT.zip>
