### ISSUE TITLE
pw-change

### ISSUE THREAD

**Issue by paskuale75** [sjaakp/yii2-pluto#24]
actionPwChange seems don't work, it check parent validation ... who is the parent ?

```
$model = new PwChangeForm([
            'user' => $user,
            'flags' => $flags
        ]);
```
... then 
`if ($model->validate()) { //....`

the validate function doing :
```
public function validate($attributeNames = null, $clearErrors = true)
    {
        $r = parent::validate($attributeNames, $clearErrors);       // first, validate form
        if ($r) $r = $this->user->validate($attributeNames, $clearErrors); // then, User (this sets new password)
        return $r;
    }
```

at line 58 the $attributeNames is null !!!! then the validate will always be null.

parent::validate ... if $model is a yii\base\Model  who is its parent ?! thanks

**Comment by paskuale75** [comment]
I have the impression that another scenario is needed...

**Comment by paskuale75** [comment]
@sjaakp PR added.

**Comment by sjaakp** [comment]
`$model` is  a `PwChangeForm`, so its parent is an `yii\base\Model`.

If `$attributeNames === null`, `Model::validate` takes the active attributes as a default (see docs and source), which in this case is `currentPassword` only.

In what sense does `actionPwChange` not work?

**Comment by paskuale75** [comment]
it seems to take an incorrect scenario, which makes saving fail because username and email are not unique.

**Comment by ettolo** [comment]
PW change is working for me at the page /pluto/pw-change but i don't understand why redirect to password change page after settings (username or email) change...

**Comment by paskuale75** [comment]
@ettolo I extends all pluto controllers/actions for customize it, but seems the scenario issue, or maybe i am using a different version than you?

**Comment by ettolo** [comment]
I have overridden only views and have everything updated with latest commit.
You get an error or only invalid model?
In my DefaultController the model validation is done after loading the posted attributes:
`if ($model->load(Yii::$app->request->post()) && $model->validate()) {`
Do you have the same? The code you posted seems different!

**Comment by paskuale75** [comment]
In my composer.json have these two settings:
```
"minimum-stability": "dev",
"prefer-stable": true,
```

can this be the cause of the difference between versions?

**Comment by paskuale75** [comment]
other case.... actionUpdate() if I try to change the status from pending to active, it gives me an error, see attached image
![Schermata da 2020-05-27 21-40-27](https://user-images.githubusercontent.com/9800/83065155-48189b00-a063-11ea-8f20-722dbe013faa.png)

**Comment by ettolo** [comment]
Paskuale I'm sorry but also this is working for me!

**Comment by paskuale75** [comment]
do I try to repeat the fork? There is something wrong with my version I think, but what is the reason?

**Comment by ettolo** [comment]
Do you keep your fork synced with the original? 
[https://help.github.com/en/github/getting-started-with-github/fork-a-repo#keep-your-fork-synced](url)

**Comment by paskuale75** [comment]
> Do you keep your fork synced with the original?
> [https://help.github.com/en/github/getting-started-with-github/fork-a-repo#keep-your-fork-synced](url)

you're right, I thought the alignment between the two was automatic...
