### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by rossaddison** [sjaakp/yii2-pluto#3]
Hi,
Please can you change your breadcrumbs convention assignment that you are using in your views from:

$this->breadcrumbs[] =  ..........

to

$this->params['breadcrumbs'][] =  ............

This will support the params variable within the yii\web\View class.

**Comment by sjaakp** [comment]
Thanks Ross, it was stupid of me to let this pass.

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: Ross Addison <notifications@github.com> 
Verzonden: zondag 23 juni 2019 05:11
Aan: sjaakp/yii2-pluto <yii2-pluto@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [sjaakp/yii2-pluto] Breadcrumbs (#3)

 

Hi,
Please can you change your breadcrumbs convention assignment that you are using in your views from:

$this->breadcrumbs[] = ..........

to

$this->params['breadcrumbs'][] = ............

This will support the params variable within the yii\web\View class.

**Comment by rossaddison** [comment]
No probs. Thanks for the quick response.

**Comment by rossaddison** [comment]
Hello Sjaak,
Geen probleem nie. Ek is bly dat ek kon help. Baie dankie vir jou app. Dit werk moei.

Mooi bly


Ross

**Comment by sjaakp** [comment]
Fijn om te horen. Ik had het niet mooier kunnen zeggen!

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: Ross Addison <notifications@github.com> 
Verzonden: zondag 30 juni 2019 22:43
Aan: sjaakp/yii2-pluto <yii2-pluto@noreply.github.com>
CC: Sjaak Priester <sjaak@sjaakpriester.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [sjaakp/yii2-pluto] Breadcrumbs (#3)

 

Hello Sjaak,
Geen probleem nie. Ek is bly dat ek kon help. Baie dankie vir jou app. Dit werk moei.

Mooi bly


Ross

**Comment by rossaddison** [comment]
Hi Sjaak,
Sal dit moontlik wees on die nuutste foutjie te hersien op Github. Twee agtereenvolgende 'deletes' gee vir ons 'n 'integrity constraint' violation. Ek het 'n proposisie gemaak.

Ek sal dit waardeur as jy tyd sal neersit om die foutjie na te kyk.

Ross


Daar is twee van ons wat graag jou
