### ISSUE TITLE
custom layout

### ISSUE THREAD

**Issue by paskuale75** [sjaakp/yii2-pluto#7]
How can define my custom layout in module section ?

Thanks

**Comment by sjaakp** [comment]
See the ‘Override view-files’ section in the documentation. Also, you may set the ‘layout’ property of the Pluto module ( <https://www.yiiframework.com/doc/api/2.0/yii-base-module#$layout-detail> https://www.yiiframework.com/doc/api/2.0/yii-base-module#$layout-detail). Doesn’t that answer your question? If not, please clarify.

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: pasquale <notifications@github.com> 
Verzonden: zondag 13 oktober 2019 12:17
Aan: sjaakp/yii2-pluto <yii2-pluto@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [sjaakp/yii2-pluto] custom layout (#7)

 

How can define my custom layout in module section ?

Thanks

**Comment by paskuale75** [comment]
Thanks
